// Generated by CoffeeScript 1.6.2
(function() {
  var CoffeeScript, indent, precompile, preprocess;

  CoffeeScript = require("coffee-script");

  preprocess = require("./preprocessor").preprocess;

  indent = require("./util").indent;

  exports.precompile = precompile = function(source) {
    var script;

    script = CoffeeScript.compile(preprocess(source), {
      bare: true
    });
    return "function(__obj) {\n  if (!__obj) __obj = {};\n\n  var __escape = __obj.escape = function(value) {\n    return (\"\" + value).replace(/&/g, \"&amp;\")\n                       .replace(/</g, \"&lt;\")\n                       .replace(/>/g, \"&gt;\")\n                       .replace(/\x22/g, \"&quot;\");\n  }\n\n  var __createFragment = __obj.createFragment = function(value, element) {\n    if (value instanceof DocumentFragment) return value;\n    element || (element = document.createElement('div'));\n    var range = document.createRange();\n    range.setStart(element, 0);\n    range.collapse(false);\n    return range.createContextualFragment(value);\n  };\n\n  return (function() {\n  " + (indent(script, 4)) + "\n  }).call(__obj);\n}";
  };

  exports.compile = function(source) {
    return new Function("return " + (precompile(source)))();
  };

}).call(this);
