// Generated by CoffeeScript 1.6.2
(function() {
  var precompile, preprocess;

  precompile = require("./compiler").precompile;

  preprocess = require("./preprocessor").preprocess;

  exports.preprocess = preprocess;

  exports.precompile = precompile;

}).call(this);
