// Generated by CoffeeScript 1.6.2
(function() {
  var cft, compile, precompile, preprocess, _ref;

  _ref = require("./compiler"), compile = _ref.compile, precompile = _ref.precompile;

  preprocess = require("./preprocessor").preprocess;

  module.exports = cft = function(source) {
    var _base, _ref1;

    if (cft.cache) {
      return (_ref1 = (_base = cft.cache)[source]) != null ? _ref1 : _base[source] = compile(source);
    } else {
      return compile(source);
    }
  };

  cft.cache = {};

  cft.preprocess = preprocess;

  cft.precompile = precompile;

  cft.compile = compile;

  cft.render = function(source, data) {
    return (cft(source))(data);
  };

}).call(this);
