// Generated by CoffeeScript 1.6.2
(function() {
  var StringCompiler, StringPreprocessor, cft, compile, precompile, preprocess, _ref;

  _ref = require("./compilers/node"), compile = _ref.compile, precompile = _ref.precompile;

  preprocess = require("./preprocessors/node").preprocess;

  StringCompiler = require("./compilers/string");

  StringPreprocessor = require("./preprocessors/string");

  module.exports = cft = function(source) {
    var _base, _ref1;

    if (cft.cache) {
      return (_ref1 = (_base = cft.cache)[source]) != null ? _ref1 : _base[source] = compile(source);
    } else {
      return compile(source);
    }
  };

  cft.cache = {};

  cft.preprocess = preprocess;

  cft.precompile = precompile;

  cft.compile = compile;

  cft.render = function(source, data) {
    return (cft(source))(data);
  };

  cft.preprocessString = StringPreprocessor.preprocess;

  cft.precompileString = StringCompiler.precompile;

  cft.compileString = StringCompiler.compile;

}).call(this);
