// Generated by CoffeeScript 1.6.2
(function() {
  var NodePreprocessor, StringPreprocessor;

  NodePreprocessor = require('./preprocessors/node');

  StringPreprocessor = require('./preprocessors/string');

  exports.preprocess = exports.preprocessNodes = function(source) {
    return NodePreprocessor.preprocess(source);
  };

  exports.preprocessString = function(source) {
    return StringPreprocessor.preprocess(source);
  };

}).call(this);
