// Generated by CoffeeScript 1.6.2
(function() {
  var Preprocessor, Scanner, util,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Scanner = require("./scanner");

  util = require("./util");

  module.exports = Preprocessor = (function() {
    Preprocessor.preprocess = function(source) {
      var preprocessor;

      preprocessor = new Preprocessor(source);
      return preprocessor.preprocess();
    };

    function Preprocessor(source) {
      this.scanner = new Scanner(source);
      this.output = "";
      this.level = 0;
      this.index = 0;
      this.captures = [];
      this.record("" + (this.elementVar()) + " = document.createDocumentFragment()");
    }

    Preprocessor.prototype.preprocess = function() {
      var token, _i, _len, _ref, _ref1;

      _ref = this.scanner.scan();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        token = _ref[_i];
        if ((_ref1 = this[token.type]) != null) {
          _ref1.call(this, token);
        }
      }
      this.record("return " + (this.elementVar()));
      return this.output;
    };

    Preprocessor.prototype.record = function(line) {
      this.output += util.repeat("  ", this.level);
      return this.output += line + "\n";
    };

    Preprocessor.prototype.indent = function() {
      return this.level++;
    };

    Preprocessor.prototype.dedent = function() {
      this.level--;
      if (this.level < 0) {
        return this.fail('Unexpected dedent');
      }
    };

    Preprocessor.prototype.elementVar = function(index) {
      if (index == null) {
        index = this.index;
      }
      return "__element" + index;
    };

    Preprocessor.prototype.traverseUp = function() {
      return this.index--;
    };

    Preprocessor.prototype.traverseDown = function() {
      return this.index++;
    };

    Preprocessor.prototype.append = function(code) {
      return this.record("" + (this.elementVar()) + ".appendChild " + code);
    };

    Preprocessor.prototype.appendParent = function(code) {
      return this.record("" + (this.elementVar(this.index - 1)) + ".appendChild " + code);
    };

    Preprocessor.prototype.capture = function(token, callback) {
      if (token.dedent) {
        this.dedent();
      }
      callback.call(this, token);
      if (token.indent || token.directive) {
        this.indent();
      }
      if (token.directive) {
        this.captures.unshift(this.level);
        this.traverseDown();
        return this.record("" + (this.elementVar()) + " = document.createDocumentFragment()");
      }
    };

    Preprocessor.prototype.fail = function(msg) {
      throw new Error(msg);
    };

    Preprocessor.prototype.eco = function(token) {
      return this["eco_" + token.tag].call(this, token);
    };

    Preprocessor.prototype.eco_end = function(token) {
      if (this.captures[0] === this.level) {
        this.captures.shift();
        this.record(this.elementVar());
      }
      this.traverseUp();
      return this.dedent();
    };

    Preprocessor.prototype.eco_leftLiteral = function(token) {
      return this.append("document.createTextNode('<%')");
    };

    Preprocessor.prototype.eco_rightLiteral = function(token) {
      return this.append("document.createTextNode('%>')");
    };

    Preprocessor.prototype.eco_expression = function(token) {
      var _this = this;

      return this.capture(token, function() {
        return _this.record(token.content + token.directive);
      });
    };

    Preprocessor.prototype.eco_escapedContent = function(token) {
      var _this = this;

      if (token.directive) {
        this.fail('Directive provided for escaped content');
      }
      return this.capture(token, function() {
        return _this.append("document.createTextNode __escape " + token.content);
      });
    };

    Preprocessor.prototype.eco_content = function(token) {
      var _this = this;

      return this.capture(token, function() {
        return _this.append(("__createFragment " + token.content) + token.directive);
      });
    };

    Preprocessor.prototype.cdata = function(token) {};

    Preprocessor.prototype.comment = function(token) {};

    Preprocessor.prototype.doctype = function(token) {};

    Preprocessor.prototype.script = function(token) {};

    Preprocessor.prototype.voidElements = ['area', 'base', 'br', 'col', 'command', 'embed', 'hr', 'img', 'input', 'keygen', 'link', 'meta', 'param', 'source', 'track', 'wbr'];

    Preprocessor.prototype.element = function(token) {
      var _ref;

      if (_ref = token.tag, __indexOf.call(this.voidElements, _ref) >= 0) {
        return this.element_inline(token);
      } else {
        return this["element_" + token.variant].call(this, token);
      }
    };

    Preprocessor.prototype.element_open = function(token) {
      var attr, element, _i, _len, _ref;

      this.traverseDown();
      element = this.elementVar();
      this.record("" + element + " = document.createElement(" + (util.inspect(token.tag)) + ")");
      _ref = token.attributes;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        attr = _ref[_i];
        this.record("" + element + ".setAttribute(" + (util.inspect(attr.name)) + ", " + (util.inspect(attr.value || true)) + ")");
      }
      return this.appendParent(element);
    };

    Preprocessor.prototype.element_close = function(token) {
      return this.traverseUp();
    };

    Preprocessor.prototype.element_inline = function(token) {
      var attr, _i, _len, _ref;

      this.record("__curr = document.createElement(" + (util.inspect(token.tag)) + ")");
      _ref = token.attributes;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        attr = _ref[_i];
        this.record("__curr.setAttribute(" + (util.inspect(attr.name)) + ", " + (util.inspect(attr.value || true)) + ")");
      }
      return this.append("__curr");
    };

    Preprocessor.prototype.style = function(token) {
      var attr, _i, _len, _ref;

      this.record("__curr = document.createElement('style')");
      _ref = token.attributes;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        attr = _ref[_i];
        this.record("__curr.setAttribute(" + (util.inspect(attr.name)) + ", " + (util.inspect(attr.value || true)) + ")");
      }
      this.record("__curr.innerHTML = " + (util.inspect(token.content)));
      return this.append("__curr");
    };

    Preprocessor.prototype.text = function(token) {
      return this.append("document.createTextNode(" + (util.inspect(token.content)) + ")");
    };

    return Preprocessor;

  })();

}).call(this);
