// Generated by CoffeeScript 1.6.2
(function() {
  var Scanner, grammar;

  grammar = require('./grammar');

  module.exports = Scanner = (function() {
    Scanner.scan = function(source) {
      var scanner, tokens;

      tokens = [];
      scanner = new Scanner(source);
      return scanner.scan();
    };

    function Scanner(source) {
      this.source = source;
    }

    Scanner.prototype.scan = function() {
      return grammar.parse(this.source);
    };

    return Scanner;

  })();

}).call(this);
