// Generated by CoffeeScript 1.6.2
(function() {
  var __escape, __makeFragment, __sanitize;

  __sanitize = function(value) {
    if (value && value.cftSafe) {
      return value;
    } else if (value != null) {
      return __escape(value);
    } else {
      return "";
    }
  };

  __escape = function(value) {
    return ("" + value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\x22/g, "&quot;");
  };

  __makeFragment = function(value, element) {
    var range;

    element || (element = document.createElement('div'));
    range = document.createRange();
    range.setStart(element, 0);
    range.collapse(false);
    return range.createContextualFragment(value);
  };

}).call(this);
